# Generated by Django 2.1.3 on 2019-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorname', models.CharField(max_length=264)),
                ('mentorphoto', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('mentorgmailid', models.CharField(max_length=264)),
                ('mentorphoneno', models.IntegerField()),
                ('state', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
                ('mentorspecialisation', models.CharField(max_length=264)),
            ],
        ),
    ]
