# Generated by Django 2.1.3 on 2019-02-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentorphoto',
            field=models.ImageField(blank=True, upload_to='photos/%Y/'),
        ),
    ]
