# Generated by Django 2.1.3 on 2019-02-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
