# Generated by Django 2.1.3 on 2019-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20190228_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='hours_of_working',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
