# Generated by Django 2.1.3 on 2019-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentor_hours_of_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='hours_of_working',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
