# Generated by Django 2.1.3 on 2019-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_mentor_mentorpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='rating',
            field=models.IntegerField(default='5'),
        ),
    ]
