# Generated by Django 2.1.3 on 2019-02-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_member',
            old_name='memebername',
            new_name='membername',
        ),
    ]
