# Generated by Django 2.1.3 on 2019-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20190301_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_details',
            name='mentor',
        ),
        migrations.AddField(
            model_name='project_details',
            name='project_des',
            field=models.CharField(default='abcd', max_length=600),
        ),
    ]
