# Generated by Django 2.1.3 on 2019-03-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0004_auto_20190303_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_details',
            name='password',
            field=models.CharField(default='123', max_length=78),
        ),
    ]
