# Generated by Django 2.1.3 on 2019-03-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_startup_details_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup_details',
            name='rating',
            field=models.IntegerField(default='5', max_length=10),
        ),
    ]
