# Generated by Django 2.1.3 on 2019-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0006_startup_details_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup_details',
            name='rating',
            field=models.IntegerField(default='5'),
        ),
    ]
