# Generated by Django 2.1.3 on 2019-03-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_auto_20190303_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup_details',
            name='rating',
        ),
    ]
